array(
'create table node (id int not null auto_increment primary key) engine InnoDB default charset utf8;',
'alter table node add column title varchar(250) not null default ""',
'create table term (id int not null auto_increment primary key) engine InnoDB default charset utf8;',
'alter table term add column title varchar(250) not null default "";',
'alter table term add column parent_id int null;',
'alter table term add foreign key (parent_id) references term(id);',
'create table termtonode (id int not null auto_increment primary key) engine InnoDB default charset utf8;',
'alter table termtonode add column node_id int not null;',
'alter table termtonode add column term_id int not null;',
'alter table termtonode add foreign key(node_id) references node(id);',
'alter table termtonode add foreign key(term_id) references term(id);',
'alter table termtonode add unique key (term_id, node_id);',
'alter table node add column body text  not null   default "";',
'alter table node add column state_code int  not null   default 0;',
'alter table node add column created_at_ts int  not null   default 0  /* rand311047 */;',
'alter table node add column is_published int  not null   default 0  /* rand693032 */;',
)
